language: node_js
node_js: '14'
install: yarn install
script:
  - yarn run test:e2e:run
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
